spring:

  thymeleaf:
    enabled: true

    check-template: true

    # View의 파일 경로를 지정하기 위한 설정
    prefix: classpath:/templates/ # ".html" 파일 경로

    # View의 파일 확장자 지정
    suffix: .html # 파일 확장자
    cache: false

  mvc:
    # 정작파일 URL 변경
    # 만약 "localhost:13151/js/jquery.min.js" 경로로 요청하게 되면 thymeleaf는 자동으로 "resource/static" 경로에서 파일을 불러온다.
    # 하지만 아래처럼 설정을 "static" 으로 설정 할 경우 "localhost:13151/static/js/jquery.min.js" 처럼 static 을 꼭 붙여야 한다.ㅣ
    # 설정 값을 abcd로 한다면 "localhost:13151/abcd/js/jquery.min.js"로 요청 해야 한다.
    static-path-pattern: /static/** # spring mvc static path 변경
    hiddenmethod:
      filter:
        enabled: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-13-209-76-58.ap-northeast-2.compute.amazonaws.com:3306/demo_ajax?characterEncoding=UTF-8&serverTimezone=UTC
    username: jeff
    password: dlaxowhd12
    hikari:
      maximum-pool-size: 5
server:
  port: 13151
  servlet:
    context-path: / # 내장 톰캣의 context path이다. 이 설정 값을 /jeff 로 하면 "localhost:13151/jeff" 경로가 기본 주소가 된다.
